# fly.toml app configuration file generated for espn-fantasy-proxy on 2025-04-05T20:09:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'espn-fantasy-proxy'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
